// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agreements.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUserAgreement = `-- name: CreateUserAgreement :one
INSERT INTO user_agreements (
    id, user_id, agreement_number, pesel_encrypted, verified_phone, status, signed_at, verified_at, verified_via
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, user_id, agreement_number, pesel_encrypted, verified_phone, status, signed_at, verified_at, verified_via, created_at, updated_at, deleted_at
`

type CreateUserAgreementParams struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	AgreementNumber string             `json:"agreement_number"`
	PeselEncrypted  []byte             `json:"pesel_encrypted"`
	VerifiedPhone   string             `json:"verified_phone"`
	Status          string             `json:"status"`
	SignedAt        pgtype.Timestamptz `json:"signed_at"`
	VerifiedAt      pgtype.Timestamptz `json:"verified_at"`
	VerifiedVia     string             `json:"verified_via"`
}

func (q *Queries) CreateUserAgreement(ctx context.Context, arg CreateUserAgreementParams) (UserAgreement, error) {
	row := q.db.QueryRow(ctx, createUserAgreement,
		arg.ID,
		arg.UserID,
		arg.AgreementNumber,
		arg.PeselEncrypted,
		arg.VerifiedPhone,
		arg.Status,
		arg.SignedAt,
		arg.VerifiedAt,
		arg.VerifiedVia,
	)
	var i UserAgreement
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgreementNumber,
		&i.PeselEncrypted,
		&i.VerifiedPhone,
		&i.Status,
		&i.SignedAt,
		&i.VerifiedAt,
		&i.VerifiedVia,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createUserPukCode = `-- name: CreateUserPukCode :one
INSERT INTO user_puk_codes (
    id, user_agreement_id, user_id, puk_hash, status, failed_attempts, max_attempts, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, user_agreement_id, user_id, puk_hash, status, failed_attempts, max_attempts, expires_at, used_at, created_at, updated_at, deleted_at
`

type CreateUserPukCodeParams struct {
	ID              uuid.UUID          `json:"id"`
	UserAgreementID uuid.UUID          `json:"user_agreement_id"`
	UserID          uuid.UUID          `json:"user_id"`
	PukHash         string             `json:"puk_hash"`
	Status          string             `json:"status"`
	FailedAttempts  int16              `json:"failed_attempts"`
	MaxAttempts     int16              `json:"max_attempts"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateUserPukCode(ctx context.Context, arg CreateUserPukCodeParams) (UserPukCode, error) {
	row := q.db.QueryRow(ctx, createUserPukCode,
		arg.ID,
		arg.UserAgreementID,
		arg.UserID,
		arg.PukHash,
		arg.Status,
		arg.FailedAttempts,
		arg.MaxAttempts,
		arg.ExpiresAt,
	)
	var i UserPukCode
	err := row.Scan(
		&i.ID,
		&i.UserAgreementID,
		&i.UserID,
		&i.PukHash,
		&i.Status,
		&i.FailedAttempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAgreementByNumber = `-- name: GetAgreementByNumber :one
SELECT id, user_id, agreement_number, pesel_encrypted, verified_phone, status, signed_at, verified_at, verified_via, created_at, updated_at, deleted_at FROM user_agreements
WHERE agreement_number = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetAgreementByNumber(ctx context.Context, agreementNumber string) (UserAgreement, error) {
	row := q.db.QueryRow(ctx, getAgreementByNumber, agreementNumber)
	var i UserAgreement
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgreementNumber,
		&i.PeselEncrypted,
		&i.VerifiedPhone,
		&i.Status,
		&i.SignedAt,
		&i.VerifiedAt,
		&i.VerifiedVia,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAgreementByUserID = `-- name: GetAgreementByUserID :one
SELECT id, user_id, agreement_number, pesel_encrypted, verified_phone, status, signed_at, verified_at, verified_via, created_at, updated_at, deleted_at FROM user_agreements
WHERE user_id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetAgreementByUserID(ctx context.Context, userID uuid.UUID) (UserAgreement, error) {
	row := q.db.QueryRow(ctx, getAgreementByUserID, userID)
	var i UserAgreement
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgreementNumber,
		&i.PeselEncrypted,
		&i.VerifiedPhone,
		&i.Status,
		&i.SignedAt,
		&i.VerifiedAt,
		&i.VerifiedVia,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPukCodeByUserID = `-- name: GetPukCodeByUserID :one
SELECT id, user_agreement_id, user_id, puk_hash, status, failed_attempts, max_attempts, expires_at, used_at, created_at, updated_at, deleted_at FROM user_puk_codes
WHERE user_id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetPukCodeByUserID(ctx context.Context, userID uuid.UUID) (UserPukCode, error) {
	row := q.db.QueryRow(ctx, getPukCodeByUserID, userID)
	var i UserPukCode
	err := row.Scan(
		&i.ID,
		&i.UserAgreementID,
		&i.UserID,
		&i.PukHash,
		&i.Status,
		&i.FailedAttempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const incrementPukFailedAttempts = `-- name: IncrementPukFailedAttempts :exec
UPDATE user_puk_codes
SET failed_attempts = failed_attempts + 1,
    status = CASE WHEN failed_attempts + 1 >= max_attempts THEN 'BLOCKED'::varchar ELSE status END,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) IncrementPukFailedAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementPukFailedAttempts, id)
	return err
}

const markPukAsUsed = `-- name: MarkPukAsUsed :exec
UPDATE user_puk_codes
SET status = 'USED', used_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) MarkPukAsUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPukAsUsed, id)
	return err
}

const updateAgreementStatus = `-- name: UpdateAgreementStatus :exec
UPDATE user_agreements
SET status = $2, verified_at = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateAgreementStatusParams struct {
	ID         uuid.UUID          `json:"id"`
	Status     string             `json:"status"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
}

func (q *Queries) UpdateAgreementStatus(ctx context.Context, arg UpdateAgreementStatusParams) error {
	_, err := q.db.Exec(ctx, updateAgreementStatus, arg.ID, arg.Status, arg.VerifiedAt)
	return err
}
