// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO citizen_audit_logs (
    id, user_id, action, actor_id, ip_address, payload_hash, prev_hash, hash
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type CreateAuditLogParams struct {
	ID          uuid.UUID   `json:"id"`
	UserID      uuid.UUID   `json:"user_id"`
	Action      string      `json:"action"`
	ActorID     uuid.UUID   `json:"actor_id"`
	IpAddress   pgtype.Text `json:"ip_address"`
	PayloadHash pgtype.Text `json:"payload_hash"`
	PrevHash    string      `json:"prev_hash"`
	Hash        string      `json:"hash"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.ID,
		arg.UserID,
		arg.Action,
		arg.ActorID,
		arg.IpAddress,
		arg.PayloadHash,
		arg.PrevHash,
		arg.Hash,
	)
	return err
}

const getLastAuditLog = `-- name: GetLastAuditLog :one
SELECT id, hash FROM citizen_audit_logs
ORDER BY created_at DESC, id DESC LIMIT 1
`

type GetLastAuditLogRow struct {
	ID   uuid.UUID `json:"id"`
	Hash string    `json:"hash"`
}

func (q *Queries) GetLastAuditLog(ctx context.Context) (GetLastAuditLogRow, error) {
	row := q.db.QueryRow(ctx, getLastAuditLog)
	var i GetLastAuditLogRow
	err := row.Scan(&i.ID, &i.Hash)
	return i, err
}

const getUnsyncedAuditLogs = `-- name: GetUnsyncedAuditLogs :many
SELECT id, user_id, action, actor_id, ip_address, payload_hash, prev_hash, hash, created_at
FROM citizen_audit_logs
WHERE synced_to_global_audit = FALSE
ORDER BY created_at ASC LIMIT $1
`

type GetUnsyncedAuditLogsRow struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Action      string             `json:"action"`
	ActorID     uuid.UUID          `json:"actor_id"`
	IpAddress   pgtype.Text        `json:"ip_address"`
	PayloadHash pgtype.Text        `json:"payload_hash"`
	PrevHash    string             `json:"prev_hash"`
	Hash        string             `json:"hash"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUnsyncedAuditLogs(ctx context.Context, limit int32) ([]GetUnsyncedAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, getUnsyncedAuditLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnsyncedAuditLogsRow
	for rows.Next() {
		var i GetUnsyncedAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ActorID,
			&i.IpAddress,
			&i.PayloadHash,
			&i.PrevHash,
			&i.Hash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAuditLogsAsSynced = `-- name: MarkAuditLogsAsSynced :exec
UPDATE citizen_audit_logs
SET synced_to_global_audit = TRUE
WHERE id = ANY($1::uuid[])
`

func (q *Queries) MarkAuditLogsAsSynced(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAuditLogsAsSynced, dollar_1)
	return err
}
