// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: citizens.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCitizenWithAudit = `-- name: CreateCitizenWithAudit :one
INSERT INTO citizens (
    user_id, pesel_hash, encrypted_data, encrypted_dek, key_version
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING user_id, created_at
`

type CreateCitizenWithAuditParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	PeselHash     string      `json:"pesel_hash"`
	EncryptedData []byte      `json:"encrypted_data"`
	EncryptedDek  []byte      `json:"encrypted_dek"`
	KeyVersion    int32       `json:"key_version"`
}

type CreateCitizenWithAuditRow struct {
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateCitizenWithAudit(ctx context.Context, arg CreateCitizenWithAuditParams) (CreateCitizenWithAuditRow, error) {
	row := q.db.QueryRow(ctx, createCitizenWithAudit,
		arg.UserID,
		arg.PeselHash,
		arg.EncryptedData,
		arg.EncryptedDek,
		arg.KeyVersion,
	)
	var i CreateCitizenWithAuditRow
	err := row.Scan(&i.UserID, &i.CreatedAt)
	return i, err
}

const getCitizenByPeselHash = `-- name: GetCitizenByPeselHash :one
SELECT user_id, pesel_hash, encrypted_data, encrypted_dek, key_version, created_at
FROM citizens WHERE pesel_hash = $1 LIMIT 1
`

type GetCitizenByPeselHashRow struct {
	UserID        pgtype.UUID        `json:"user_id"`
	PeselHash     string             `json:"pesel_hash"`
	EncryptedData []byte             `json:"encrypted_data"`
	EncryptedDek  []byte             `json:"encrypted_dek"`
	KeyVersion    int32              `json:"key_version"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetCitizenByPeselHash(ctx context.Context, peselHash string) (GetCitizenByPeselHashRow, error) {
	row := q.db.QueryRow(ctx, getCitizenByPeselHash, peselHash)
	var i GetCitizenByPeselHashRow
	err := row.Scan(
		&i.UserID,
		&i.PeselHash,
		&i.EncryptedData,
		&i.EncryptedDek,
		&i.KeyVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getCitizenByUserID = `-- name: GetCitizenByUserID :one
SELECT user_id, pesel_hash, encrypted_data, encrypted_dek, key_version, created_at
FROM citizens WHERE user_id = $1 LIMIT 1
`

type GetCitizenByUserIDRow struct {
	UserID        pgtype.UUID        `json:"user_id"`
	PeselHash     string             `json:"pesel_hash"`
	EncryptedData []byte             `json:"encrypted_data"`
	EncryptedDek  []byte             `json:"encrypted_dek"`
	KeyVersion    int32              `json:"key_version"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetCitizenByUserID(ctx context.Context, userID pgtype.UUID) (GetCitizenByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getCitizenByUserID, userID)
	var i GetCitizenByUserIDRow
	err := row.Scan(
		&i.UserID,
		&i.PeselHash,
		&i.EncryptedData,
		&i.EncryptedDek,
		&i.KeyVersion,
		&i.CreatedAt,
	)
	return i, err
}
