// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Citizen struct {
	UserID        pgtype.UUID        `json:"user_id"`
	PeselHash     string             `json:"pesel_hash"`
	EncryptedData []byte             `json:"encrypted_data"`
	EncryptedDek  []byte             `json:"encrypted_dek"`
	Nonce         []byte             `json:"nonce"`
	KeyVersion    int32              `json:"key_version"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type CitizenAuditLog struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	Action              string             `json:"action"`
	ActorID             pgtype.UUID        `json:"actor_id"`
	IpAddress           pgtype.Text        `json:"ip_address"`
	PayloadHash         pgtype.Text        `json:"payload_hash"`
	PrevHash            string             `json:"prev_hash"`
	Hash                string             `json:"hash"`
	SyncedToGlobalAudit bool               `json:"synced_to_global_audit"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type UserAgreement struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	AgreementNumber string             `json:"agreement_number"`
	PeselEncrypted  string             `json:"pesel_encrypted"`
	VerifiedPhone   string             `json:"verified_phone"`
	Status          string             `json:"status"`
	SignedAt        pgtype.Timestamptz `json:"signed_at"`
	VerifiedAt      pgtype.Timestamptz `json:"verified_at"`
	VerifiedVia     string             `json:"verified_via"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type UserPukCode struct {
	ID              pgtype.UUID        `json:"id"`
	UserAgreementID pgtype.UUID        `json:"user_agreement_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	PukHash         string             `json:"puk_hash"`
	Status          string             `json:"status"`
	FailedAttempts  int16              `json:"failed_attempts"`
	MaxAttempts     int16              `json:"max_attempts"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	UsedAt          pgtype.Timestamptz `json:"used_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}
