// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Citizen struct {
	UserID        pgtype.UUID        `json:"user_id"`
	PeselHash     string             `json:"pesel_hash"`
	EncryptedData []byte             `json:"encrypted_data"`
	EncryptedDek  []byte             `json:"encrypted_dek"`
	Nonce         []byte             `json:"nonce"`
	KeyVersion    int32              `json:"key_version"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type CitizenAuditLog struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	Action              string             `json:"action"`
	ActorID             pgtype.UUID        `json:"actor_id"`
	IpAddress           pgtype.Text        `json:"ip_address"`
	PayloadHash         pgtype.Text        `json:"payload_hash"`
	SyncedToGlobalAudit bool               `json:"synced_to_global_audit"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}
