// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const createOutboxMessage = `-- name: CreateOutboxMessage :one
INSERT INTO outbox_messages (
    id, aggregate_type, aggregate_id, event_type, payload, status
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, aggregate_type, aggregate_id, event_type, payload, status, retry_count, last_error, processed_at, created_at, updated_at, deleted_at
`

type CreateOutboxMessageParams struct {
	ID            uuid.UUID `json:"id"`
	AggregateType string    `json:"aggregate_type"`
	AggregateID   uuid.UUID `json:"aggregate_id"`
	EventType     string    `json:"event_type"`
	Payload       []byte    `json:"payload"`
	Status        string    `json:"status"`
}

func (q *Queries) CreateOutboxMessage(ctx context.Context, arg CreateOutboxMessageParams) (OutboxMessage, error) {
	row := q.db.QueryRow(ctx, createOutboxMessage,
		arg.ID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.Status,
	)
	var i OutboxMessage
	err := row.Scan(
		&i.ID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.RetryCount,
		&i.LastError,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const fetchPendingOutboxMessages = `-- name: FetchPendingOutboxMessages :many
SELECT id, aggregate_type, aggregate_id, event_type, payload, retry_count
FROM outbox_messages
WHERE status = 'PENDING' AND deleted_at IS NULL
ORDER BY created_at ASC
LIMIT $1
`

type FetchPendingOutboxMessagesRow struct {
	ID            uuid.UUID `json:"id"`
	AggregateType string    `json:"aggregate_type"`
	AggregateID   uuid.UUID `json:"aggregate_id"`
	EventType     string    `json:"event_type"`
	Payload       []byte    `json:"payload"`
	RetryCount    int16     `json:"retry_count"`
}

func (q *Queries) FetchPendingOutboxMessages(ctx context.Context, limit int32) ([]FetchPendingOutboxMessagesRow, error) {
	rows, err := q.db.Query(ctx, fetchPendingOutboxMessages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchPendingOutboxMessagesRow
	for rows.Next() {
		var i FetchPendingOutboxMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.RetryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxMessageAsFailed = `-- name: MarkOutboxMessageAsFailed :exec
UPDATE outbox_messages
SET status = CASE WHEN retry_count + 1 >= $2 THEN 'FAILED' ELSE 'PENDING' END,
    retry_count = retry_count + 1,
    last_error = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type MarkOutboxMessageAsFailedParams struct {
	ID         uuid.UUID `json:"id"`
	RetryCount int16     `json:"retry_count"`
	LastError  *string   `json:"last_error"`
}

func (q *Queries) MarkOutboxMessageAsFailed(ctx context.Context, arg MarkOutboxMessageAsFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxMessageAsFailed, arg.ID, arg.RetryCount, arg.LastError)
	return err
}

const markOutboxMessageAsSent = `-- name: MarkOutboxMessageAsSent :exec
UPDATE outbox_messages
SET status = 'SENT', processed_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) MarkOutboxMessageAsSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxMessageAsSent, id)
	return err
}
