// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateCitizenWithAudit(ctx context.Context, arg CreateCitizenWithAuditParams) (CreateCitizenWithAuditRow, error)
	GetCitizenByPeselHash(ctx context.Context, peselHash string) (GetCitizenByPeselHashRow, error)
	GetCitizenByUserID(ctx context.Context, userID pgtype.UUID) (GetCitizenByUserIDRow, error)
	GetUnsyncedAuditLogs(ctx context.Context, limit int32) ([]GetUnsyncedAuditLogsRow, error)
	MarkAuditLogsAsSynced(ctx context.Context, dollar_1 []pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
