// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO citizen_audit_logs (
    id, user_id, action, actor_id, ip_address, payload_hash
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreateAuditLogParams struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	Action      string      `json:"action"`
	ActorID     pgtype.UUID `json:"actor_id"`
	IpAddress   pgtype.Text `json:"ip_address"`
	PayloadHash pgtype.Text `json:"payload_hash"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.ID,
		arg.UserID,
		arg.Action,
		arg.ActorID,
		arg.IpAddress,
		arg.PayloadHash,
	)
	return err
}

const createCitizenWithAudit = `-- name: CreateCitizenWithAudit :one
INSERT INTO citizens (
    user_id, pesel_hash, encrypted_data, encrypted_dek, nonce, key_version
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING user_id, created_at
`

type CreateCitizenWithAuditParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	PeselHash     string      `json:"pesel_hash"`
	EncryptedData []byte      `json:"encrypted_data"`
	EncryptedDek  []byte      `json:"encrypted_dek"`
	Nonce         []byte      `json:"nonce"`
	KeyVersion    int32       `json:"key_version"`
}

type CreateCitizenWithAuditRow struct {
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateCitizenWithAudit(ctx context.Context, arg CreateCitizenWithAuditParams) (CreateCitizenWithAuditRow, error) {
	row := q.db.QueryRow(ctx, createCitizenWithAudit,
		arg.UserID,
		arg.PeselHash,
		arg.EncryptedData,
		arg.EncryptedDek,
		arg.Nonce,
		arg.KeyVersion,
	)
	var i CreateCitizenWithAuditRow
	err := row.Scan(&i.UserID, &i.CreatedAt)
	return i, err
}

const getCitizenByPeselHash = `-- name: GetCitizenByPeselHash :one
SELECT user_id, pesel_hash, encrypted_data, encrypted_dek, nonce, key_version, created_at
FROM citizens
WHERE pesel_hash = $1 LIMIT 1
`

type GetCitizenByPeselHashRow struct {
	UserID        pgtype.UUID        `json:"user_id"`
	PeselHash     string             `json:"pesel_hash"`
	EncryptedData []byte             `json:"encrypted_data"`
	EncryptedDek  []byte             `json:"encrypted_dek"`
	Nonce         []byte             `json:"nonce"`
	KeyVersion    int32              `json:"key_version"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetCitizenByPeselHash(ctx context.Context, peselHash string) (GetCitizenByPeselHashRow, error) {
	row := q.db.QueryRow(ctx, getCitizenByPeselHash, peselHash)
	var i GetCitizenByPeselHashRow
	err := row.Scan(
		&i.UserID,
		&i.PeselHash,
		&i.EncryptedData,
		&i.EncryptedDek,
		&i.Nonce,
		&i.KeyVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getCitizenByUserID = `-- name: GetCitizenByUserID :one
SELECT user_id, pesel_hash, encrypted_data, encrypted_dek, nonce, key_version, created_at
FROM citizens
WHERE user_id = $1 LIMIT 1
`

type GetCitizenByUserIDRow struct {
	UserID        pgtype.UUID        `json:"user_id"`
	PeselHash     string             `json:"pesel_hash"`
	EncryptedData []byte             `json:"encrypted_data"`
	EncryptedDek  []byte             `json:"encrypted_dek"`
	Nonce         []byte             `json:"nonce"`
	KeyVersion    int32              `json:"key_version"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetCitizenByUserID(ctx context.Context, userID pgtype.UUID) (GetCitizenByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getCitizenByUserID, userID)
	var i GetCitizenByUserIDRow
	err := row.Scan(
		&i.UserID,
		&i.PeselHash,
		&i.EncryptedData,
		&i.EncryptedDek,
		&i.Nonce,
		&i.KeyVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getUnsyncedAuditLogs = `-- name: GetUnsyncedAuditLogs :many
SELECT id, user_id, action, actor_id, ip_address, payload_hash, created_at
FROM citizen_audit_logs
WHERE synced_to_global_audit = FALSE
ORDER BY created_at ASC
LIMIT $1
`

type GetUnsyncedAuditLogsRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Action      string             `json:"action"`
	ActorID     pgtype.UUID        `json:"actor_id"`
	IpAddress   pgtype.Text        `json:"ip_address"`
	PayloadHash pgtype.Text        `json:"payload_hash"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUnsyncedAuditLogs(ctx context.Context, limit int32) ([]GetUnsyncedAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, getUnsyncedAuditLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnsyncedAuditLogsRow
	for rows.Next() {
		var i GetUnsyncedAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ActorID,
			&i.IpAddress,
			&i.PayloadHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAuditLogsAsSynced = `-- name: MarkAuditLogsAsSynced :exec
UPDATE citizen_audit_logs
SET synced_to_global_audit = TRUE
WHERE id = ANY($1::uuid[])
`

func (q *Queries) MarkAuditLogsAsSynced(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAuditLogsAsSynced, dollar_1)
	return err
}
