x-common-settings: &common-settings
  restart: ${DOCKER_RESTART_POLICY:-no}
  environment:
    - ENV=${APP_ENV:-development}
  networks:
    - citizen-app-net

services:
  # region SVC GATEWAY
  # --- GATEWAY ---
  gateway:
    build:
      context: ../../
      dockerfile: platform/services/gateway/Dockerfile.dev
    image: gateway:dev
    container_name: app-gateway
    restart: ${DOCKER_RESTART_POLICY:-no}
    working_dir: /app/services/gateway
    environment:
      - GOCACHE=/root/.cache/go-build
      - GOWORK=off
    volumes:
      - ../services/gateway:/app/services/gateway
      - ../pkg:/app/pkg
      - ../go.work:/app/go.work
      - ../go.work.sum:/app/go.work.sum
      - go-build-cache:/root/.cache/go-build
      - go-mod-cache:/go/pkg/mod
    ports:
      - "8080:8090"
    env_file:
      - ../services/gateway/.env.dev
    networks:
      - gateway-net
      - target-admin-net
      - cache-net
    depends_on:
      cache-redis:
        condition: service_started

  # region SVC AUTH
  # --- AUTHENTICATION SERVICE ---
  auth-service:
    build:
      context: ../../
      dockerfile: platform/services/auth-service/Dockerfile.dev
    image: auth-service:dev
    container_name: app-auth-service
    restart: ${DOCKER_RESTART_POLICY:-no}
    working_dir: /app/services/auth-service
    environment:
      - SECRET_AGENT_SOCKET_PATH=/var/run/agent-sockets/agent.sock
      - AUTH_SERVICE_CLIENT_ID=auth-service
      - GOCACHE=/root/.cache/go-build
      - GOWORK=off
    volumes:
      - ../services/auth-service:/app/services/auth-service
      - ../pkg:/app/pkg
      - ../go.work:/app/go.work
      - ../go.work.sum:/app/go.work.sum
      - socket-data:/var/run/agent-sockets:ro
      # Cache Go
      - go-build-cache:/root/.cache/go-build
      - go-mod-cache:/go/pkg/mod
    ports:
      - "8082:8082"
    env_file:
      - ../services/auth-service/.env.dev
    networks:
      - gateway-net
      - auth-db-net
      - sec-net
      - cache-net
    depends_on:
      db-auth:
        condition: service_healthy
    
    # region SVC OFFICER-BFF
  # --- OFFICER BFF SERVICE ---
  officer-bff:
    build:
      context: ../../
      dockerfile: platform/services/officer-bff/Dockerfile.dev
    image: officer-bff:dev
    container_name: app-officer-bff
    restart: ${DOCKER_RESTART_POLICY:-no}
    working_dir: /app/services/officer-bff
    environment:
      - GOCACHE=/root/.cache/go-build
      - GOWORK=off
    volumes:
      - ../services/officer-bff:/app/services/officer-bff
      - ../pkg:/app/pkg
      - ../go.work:/app/go.work
      - ../go.work.sum:/app/go.work.sum
      # Cache Go
      - go-build-cache:/root/.cache/go-build
      - go-mod-cache:/go/pkg/mod
    ports:
      - "8084:8084"
    env_file:
      - ../services/officer-bff/.env.dev
    networks:
      - gateway-net
      - target-admin-net
      - cache-net
    depends_on:
      cache-redis:
        condition: service_started

  # region SVC IDENTITY
  # --- IDENTITY SERVICE ---
  identity-service:
    build:
      context: ../../
      dockerfile: platform/services/identity-service/Dockerfile.dev
    image: identity-service:dev
    container_name: app-identity-service
    restart: ${DOCKER_RESTART_POLICY:-no}
    working_dir: /app/services/identity-service
    environment:
      - SECRET_AGENT_SOCKET_PATH=/var/run/agent-sockets/agent.sock
      - GOCACHE=/root/.cache/go-build
      - GOWORK=off
    volumes:
      - ../services/identity-service:/app/services/identity-service
      - ../pkg:/app/pkg
      - ../go.work:/app/go.work
      - ../go.work.sum:/app/go.work.sum
      - socket-data:/var/run/agent-sockets:ro
      # Cache Go
      - go-build-cache:/root/.cache/go-build
      - go-mod-cache:/go/pkg/mod
    ports:
      - "8070:8070"
    env_file:
      - ../services/identity-service/.env.dev
    networks:
      - gateway-net
      - identity-db-net
      - sec-net
      - cache-net
    depends_on:
      db-identity:
        condition: service_healthy

  # region db-auth
  # --- AUTHENTICATION DATABASE ---
  db-auth:
    image: postgres:18.3-alpine
    container_name: db-auth
    restart: ${DOCKER_RESTART_POLICY:-no}
    environment:
      POSTGRES_USER: ${AUTH_DB_ROOT_USER:-auth_db_root}
      POSTGRES_DB: ${AUTH_DB_NAME:-auth_database}
      POSTGRES_PASSWORD_FILE: /run/secrets/auth_db_root_pass
      KMS_ADMIN_USER: ${KMS_ADMIN_USER:-kms_admin}
    secrets:
      - auth_db_root_pass
      - kms_admin_pass
    ports:
      - "5450:5432"
    networks:
      - target-admin-net
      - auth-db-net
    volumes:
      - pg_auth_data:/var/lib/postgresql
      - ./scripts/init-kms-admin.sh:/docker-entrypoint-initdb.d/01-init-kms-admin.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
   # region db-identity
  # --- IDENTITY DATABASE ---
  db-identity:
    image: postgres:18.3-alpine
    container_name: db-identity
    environment:
      POSTGRES_USER: ${IDENTITY_DB_USER:-identity_user}
      POSTGRES_DB: ${IDENTITY_DB_NAME:-identity_database}
      POSTGRES_PASSWORD_FILE: /run/secrets/identity_db_pass
    secrets:
      - identity_db_pass
    ports:
      - "5451:5432"
    networks:
      - target-admin-net
      - identity-db-net
    volumes:
      - pg_identity_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  # region db-notification
  # --- NOTIFICATION DATABASE ---
  db-notification:
    <<: *common-settings
    image: postgres:18.3-alpine
    container_name: db-notification
    environment:
      POSTGRES_USER: ${NOTIFY_DB_USER:-notification_user}
      POSTGRES_DB: ${NOTIFY_DB_NAME:-notification_database}
      POSTGRES_PASSWORD_FILE: /run/secrets/notify_db_pass
    secrets:
      - notify_db_pass
    ports:
      - "5434:5432"
    volumes:
      - pg_notification_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  # region db-citizen-docs
  # # --- CITIZEN DOCUMENTS DATABASE ---
  db-citizen-docs:
    <<: *common-settings
    image: postgres:18.3-alpine
    container_name: db-citizen-docs
    environment:
      POSTGRES_USER: ${CITIZEN_DB_USER:-citizen_user}
      POSTGRES_DB: ${CITIZEN_DB_NAME:-citizen_docs_database}
      POSTGRES_PASSWORD_FILE: /run/secrets/citizen_db_pass
    secrets:
      - citizen_db_pass
    ports:
      - "5433:5432"
    volumes:
      - pg_citizen_docs_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  # region db-audit
  # --- AUDIT DATABASE ---
  db-audit:
    <<: *common-settings
    image: postgres:18.3-alpine
    container_name: db-audit
    environment:
      POSTGRES_USER: ${AUDIT_DB_USER:-audit_user}
      POSTGRES_DB: ${AUDIT_DB_NAME:-audit_database}
      POSTGRES_PASSWORD_FILE: /run/secrets/audit_db_pass
    secrets:
      - audit_db_pass
    ports:
      - "5435:5432"
    volumes:
      - pg_audit_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  # region db-messaging
  # --- MESSAGING DATABASE ---
  db-messaging:
    <<: *common-settings
    image: postgres:18.3-alpine
    container_name: db-messaging
    environment:
      POSTGRES_USER: ${MESSAGING_DB_USER:-messaging_user}
      POSTGRES_DB: ${MESSAGING_DB_NAME:-messaging_database}
      POSTGRES_PASSWORD_FILE: /run/secrets/messaging_db_pass
    secrets:
      - messaging_db_pass
    ports:
      - "5436:5432"
    volumes:
      - pg_messaging_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  # region cache-redis
  # --- SESSION & CACHING ---
  cache-redis:
    <<: *common-settings
    image: redis:8.6-alpine
    container_name: cache-redis
    secrets:
      - redis_auth_pass
    command: >
      sh -c 'redis-server --requirepass $$(cat /run/secrets/redis_auth_pass)'
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cache-net

    # region rabbitmq
  rabbitmq:
    <<: *common-settings
    image: rabbitmq:4.3.1-management
    container_name: rabbitmq_server
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER_FILE: /run/secrets/rabbitmq_root_user
      RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/rabbitmq_root_pass
    secrets:
      - rabbitmq_root_user
      - rabbitmq_root_pass
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # region STORAGE S3
  minio:
    image: minio/minio:latest
    container_name: storage_minio_s3
    restart: ${DOCKER_RESTART_POLICY:-no}
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER_FILE: /run/secrets/minio_root_user
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio_root_pass
    secrets:
      - minio_root_user
      - minio_root_pass
    networks:
      - cache-net
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # region ADMINISTRATION TOOLS
  #
  #
  #
  # region pgadmin
  # pgadmin:
  #   <<: *common-settings
  #   image: dpage/pgadmin4:9.14
  #   container_name: pgadmin-management
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_root_pass
  #     PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
  #   secrets:
  #     - pgadmin_root_pass
  #   command: >
  #     sh -c "export PGADMIN_DEFAULT_PASSWORD=$$(cat /run/secrets/pgadmin_root_pass) &&
  #            /entrypoint.sh"
  #   volumes:
  #     - ./pgadmin_data:/var/lib/pgadmin
  #   depends_on:
  #     db-auth:
  #       condition: service_healthy

  # region otel-collector
  # # --- OBSERVABILITY ---
  # otel-collector:
  #   <<: *common-settings
  #   image: otel/opentelemetry-collector-contrib:latest
  #   container_name: telemetry-collector
  #   command: ["--config=/etc/otel-collector-config.yaml"]
  #   volumes:
  #     - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
  #   ports:
  #     - "4318:4318"
  #     - "4317:4317"

  # jaeger:
  #   <<: *common-settings
  #   image: jaegertracing/all-in-one:latest
  #   container_name: telemetry-jaeger
  #   ports:
  #     - "16686:16686"
  #     - "4319:4317"

  # region secrets
secrets:
  auth_db_root_pass:
    file: ./secrets/.auth_db_password # HeadAdmin
  kms_admin_pass:
    file: ./secrets/.kms_admin_auth_pass # Admin for KMS
  citizen_db_pass:
    file: ./secrets/.citizen_db_password
  notify_db_pass:
    file: ./secrets/.notify_db_password
  audit_db_pass:
    file: ./secrets/.audit_db_password
  redis_auth_pass:
    file: ./secrets/.redis_password
  pgadmin_root_pass:
    file: ./secrets/.pgadmin_admin_password
  messaging_db_pass:
    file: ./secrets/.messaging_db_password
  identity_db_pass:
    file: ./secrets/.identity_db_password

  minio_root_user:
    file: ./secrets/.minio_user
  minio_root_pass:
    file: ./secrets/.minio_password
  rabbitmq_root_user:
    file: ./secrets/.rabbitmq_user
  rabbitmq_root_pass:
    file: ./secrets/.rabbitmq_password

  # region volumes
volumes:
  pg_test_data:
  pg_auth_data:
  pg_citizen_docs_data:
  pg_notification_data:
  pg_audit_data:
  pg_messaging_data:
  pg_identity_data:
  redis_data:
  go-modules:
  rabbitmq_data:
  minio_data:
  socket-data:
    external: true
    name: secret_agent_sockets
  go-build-cache:
  go-mod-cache:

  # region networks
networks:
  gateway-net:
    name: app_gateway_net
    driver: bridge
  auth-db-net:
    name: app_auth_db_net
    driver: bridge
    internal: false
  identity-db-net:
    name: app_identity_db_net
    driver: bridge
    internal: false
  cache-net:
    name: app_cache_net
    driver: bridge
    internal: false
  target-admin-net:
    name: kms_target-admin-net
    external: true
  sec-net:
    name: kms_sec-net
    external: true

  citizen-app-net:
    name: obywatel_app__network
    driver: bridge
