x-common-settings: &common-settings
  restart: ${DOCKER_RESTART_POLICY:-no}
  environment:
    - ENV=${APP_ENV:-development}
  networks:
    - citizen-app-net

services:
  # --- GATEWAY ---
  gateway:
    <<: *common-settings
    image: golang:1.26.2-alpine3.23
    container_name: app-gateway
    working_dir: /app
    volumes:
      - ../services/gateway:/app
      - ../platform:/platform
      - go-modules:/go/pkg
    ports:
      - "8080:8080"
    depends_on:
      db-auth:
        condition: service_healthy
      cache-redis:
        condition: service_started
  # --- AUTHENTICATION DATABASE ---
  db-auth:
    <<: *common-settings
    image: postgres:18.3-alpine
    container_name: auth-database
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_PASSWORD_FILE: /run/secrets/auth_db_pass
    secrets:
      - auth_db_pass
    ports:
      - "5432:5432"
    volumes:
      - pg_auth_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  # # --- CITIZEN DOCUMENTS DATABASE ---
  # db-citizen-docs:
  #   <<: *common-settings
  #   image: postgres:18.3-alpine
  #   container_name: citizen-docs-database
  #   environment:
  #     POSTGRES_USER: ${CITIZEN_DB_USER}
  #     POSTGRES_DB: ${CITIZEN_DB_NAME}
  #     POSTGRES_PASSWORD_FILE: /run/secrets/citizen_db_pass
  #   secrets:
  #     - citizen_db_pass
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - pg_citizen_docs_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  # # --- NOTIFICATION DATABASE ---
  # db-notification:
  #   <<: *common-settings
  #   image: postgres:18.3-alpine
  #   container_name: notification-database
  #   environment:
  #     POSTGRES_USER: ${NOTIFY_DB_USER}
  #     POSTGRES_DB: ${NOTIFY_DB_NAME}
  #     POSTGRES_PASSWORD_FILE: /run/secrets/notify_db_pass
  #   secrets:
  #     - notify_db_pass
  #   ports:
  #     - "5434:5432"
  #   volumes:
  #     - pg_notification_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  # --- SESSION & CACHING ---
  cache-redis:
    <<: *common-settings
    image: redis:8.4-alpine
    container_name: auth-redis
    secrets:
      - redis_auth_pass
    command: >
      sh -c 'redis-server --requirepass $$(cat /run/secrets/redis_auth_pass)'
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # --- ADMINISTRATION TOOLS ---
  pgadmin:
    <<: *common-settings
    image: dpage/pgadmin4:9.14
    container_name: pgadmin-management
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_root_pass
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
    secrets:
      - pgadmin_root_pass
    command: >
      sh -c "export PGADMIN_DEFAULT_PASSWORD=$$(cat /run/secrets/pgadmin_root_pass) && 
             /entrypoint.sh"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    depends_on:
      db-auth:
        condition: service_healthy

  # # --- OBSERVABILITY ---
  # otel-collector:
  #   <<: *common-settings
  #   image: otel/opentelemetry-collector-contrib:latest
  #   container_name: telemetry-collector
  #   command: ["--config=/etc/otel-collector-config.yaml"]
  #   volumes:
  #     - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
  #   ports:
  #     - "4318:4318"
  #     - "4317:4317"

  # jaeger:
  #   <<: *common-settings
  #   image: jaegertracing/all-in-one:latest
  #   container_name: telemetry-jaeger
  #   ports:
  #     - "16686:16686"
  #     - "4319:4317"

secrets:
  auth_db_pass:
    file: ./secrets/.auth_db_password
  citizen_db_pass:
    file: ./secrets/.citizen_db_password
  notify_db_pass:
    file: ./secrets/.notify_db_password
  redis_auth_pass:
    file: ./secrets/.redis_password
  pgadmin_root_pass:
    file: ./secrets/.pgadmin_admin_password

volumes:
  pg_auth_data:
  pg_citizen_docs_data:
  pg_notification_data:
  redis_data:
  go-modules:

networks:
  citizen-app-net:
    name: obywatel_app__network
    driver: bridge
