FROM golang:1.27-alpine

# Instalujemy air do hot-reloadu
RUN go install github.com/air-verse/air@latest

WORKDIR /app/services/gateway

# Domyślna komenda uruchomieniowa air z osobną binarką dla gateway
CMD ["air", "--build.cmd", "go build -o /tmp/gateway ./cmd/main.go", "--build.bin", "/tmp/gateway"]