// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EncryptedAuditLog struct {
	ID            int64              `json:"id"`
	UserID        int64              `json:"user_id"`
	ServiceName   string             `json:"service_name"`
	Action        string             `json:"action"`
	IpAddress     string             `json:"ip_address"`
	EncryptedData []byte             `json:"encrypted_data"`
	EncryptedKey  []byte             `json:"encrypted_key"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}
