// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID          int64              `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	ServiceName string             `json:"service_name"`
	Action      string             `json:"action"`
	IpAddress   string             `json:"ip_address"`
	Metadata    []byte             `json:"metadata"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
