// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package dbgen

import (
	"context"
)

const createEncryptedLog = `-- name: CreateEncryptedLog :exec
INSERT INTO encrypted_audit_logs (
    user_id, service_name, action, ip_address, encrypted_data, encrypted_key, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type CreateEncryptedLogParams struct {
	UserID        int64  `json:"user_id"`
	ServiceName   string `json:"service_name"`
	Action        string `json:"action"`
	IpAddress     string `json:"ip_address"`
	EncryptedData []byte `json:"encrypted_data"`
	EncryptedKey  []byte `json:"encrypted_key"`
	Status        string `json:"status"`
}

func (q *Queries) CreateEncryptedLog(ctx context.Context, arg CreateEncryptedLogParams) error {
	_, err := q.db.Exec(ctx, createEncryptedLog,
		arg.UserID,
		arg.ServiceName,
		arg.Action,
		arg.IpAddress,
		arg.EncryptedData,
		arg.EncryptedKey,
		arg.Status,
	)
	return err
}

const getAllLogs = `-- name: GetAllLogs :many
SELECT id, user_id, service_name, action, ip_address, encrypted_data, encrypted_key, status, created_at FROM encrypted_audit_logs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllLogs(ctx context.Context, arg GetAllLogsParams) ([]EncryptedAuditLog, error) {
	rows, err := q.db.Query(ctx, getAllLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EncryptedAuditLog
	for rows.Next() {
		var i EncryptedAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServiceName,
			&i.Action,
			&i.IpAddress,
			&i.EncryptedData,
			&i.EncryptedKey,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLogByID = `-- name: GetLogByID :one
SELECT id, user_id, service_name, action, ip_address, encrypted_data, encrypted_key, status, created_at FROM encrypted_audit_logs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetLogByID(ctx context.Context, id int64) (EncryptedAuditLog, error) {
	row := q.db.QueryRow(ctx, getLogByID, id)
	var i EncryptedAuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceName,
		&i.Action,
		&i.IpAddress,
		&i.EncryptedData,
		&i.EncryptedKey,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getLogsByAction = `-- name: GetLogsByAction :many
SELECT id, user_id, service_name, action, ip_address, encrypted_data, encrypted_key, status, created_at FROM encrypted_audit_logs
WHERE action = $1
ORDER BY created_at DESC
`

func (q *Queries) GetLogsByAction(ctx context.Context, action string) ([]EncryptedAuditLog, error) {
	rows, err := q.db.Query(ctx, getLogsByAction, action)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EncryptedAuditLog
	for rows.Next() {
		var i EncryptedAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServiceName,
			&i.Action,
			&i.IpAddress,
			&i.EncryptedData,
			&i.EncryptedKey,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLogsByUserId = `-- name: GetLogsByUserId :many
SELECT id, user_id, service_name, action, ip_address, encrypted_data, encrypted_key, status, created_at FROM encrypted_audit_logs
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetLogsByUserId(ctx context.Context, userID int64) ([]EncryptedAuditLog, error) {
	rows, err := q.db.Query(ctx, getLogsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EncryptedAuditLog
	for rows.Next() {
		var i EncryptedAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServiceName,
			&i.Action,
			&i.IpAddress,
			&i.EncryptedData,
			&i.EncryptedKey,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
