// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLog = `-- name: CreateLog :exec
INSERT INTO audit_logs (
    user_id, service_name, action, ip_address, metadata, status
) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateLogParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	ServiceName string      `json:"service_name"`
	Action      string      `json:"action"`
	IpAddress   string      `json:"ip_address"`
	Metadata    []byte      `json:"metadata"`
	Status      string      `json:"status"`
}

func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) error {
	_, err := q.db.Exec(ctx, createLog,
		arg.UserID,
		arg.ServiceName,
		arg.Action,
		arg.IpAddress,
		arg.Metadata,
		arg.Status,
	)
	return err
}

const getAllLogs = `-- name: GetAllLogs :many
SELECT id, user_id, service_name, action, ip_address, metadata, status, created_at FROM audit_logs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllLogs(ctx context.Context, arg GetAllLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, getAllLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServiceName,
			&i.Action,
			&i.IpAddress,
			&i.Metadata,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLogByID = `-- name: GetLogByID :one
SELECT id, user_id, service_name, action, ip_address, metadata, status, created_at FROM audit_logs
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetLogByID(ctx context.Context, id int64) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getLogByID, id)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceName,
		&i.Action,
		&i.IpAddress,
		&i.Metadata,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getLogsByAction = `-- name: GetLogsByAction :many
SELECT id, user_id, service_name, action, ip_address, metadata, status, created_at FROM audit_logs
WHERE action = $1
ORDER BY created_at DESC
`

func (q *Queries) GetLogsByAction(ctx context.Context, action string) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, getLogsByAction, action)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServiceName,
			&i.Action,
			&i.IpAddress,
			&i.Metadata,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLogsByUserId = `-- name: GetLogsByUserId :many
SELECT id, user_id, service_name, action, ip_address, metadata, status, created_at FROM audit_logs
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetLogsByUserId(ctx context.Context, userID pgtype.UUID) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, getLogsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServiceName,
			&i.Action,
			&i.IpAddress,
			&i.Metadata,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
