// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateLog(ctx context.Context, arg CreateLogParams) error
	GetAllLogs(ctx context.Context, arg GetAllLogsParams) ([]AuditLog, error)
	GetLogByID(ctx context.Context, id int64) (AuditLog, error)
	GetLogsByAction(ctx context.Context, action string) ([]AuditLog, error)
	GetLogsByUserId(ctx context.Context, userID pgtype.UUID) ([]AuditLog, error)
}

var _ Querier = (*Queries)(nil)
