// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"
)

type Querier interface {
	CreateEncryptedLog(ctx context.Context, arg CreateEncryptedLogParams) error
	GetAllLogs(ctx context.Context, arg GetAllLogsParams) ([]EncryptedAuditLog, error)
	GetLogByID(ctx context.Context, id int64) (EncryptedAuditLog, error)
	GetLogsByAction(ctx context.Context, action string) ([]EncryptedAuditLog, error)
	GetLogsByUserId(ctx context.Context, userID int64) ([]EncryptedAuditLog, error)
}

var _ Querier = (*Queries)(nil)
