root = "."
tmp_dir = "/tmp"

[build]
  cmd = "go build -o /tmp/document-renderer ./cmd/server/main.go"
  bin = "/tmp/document-renderer"
  include_ext = ["go", "html", "css", "tmpl"]
  exclude_dir = ["assets", "tmp"]
  delay = 1000 # ms

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"