FROM golang:1.22-alpine

# Instalujemy Chromium, czcionki oraz git do go module
RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    font-noto-emoji \
    git

# Instalujemy air do hot-reloadu
RUN go install github.com/air-verse/air@latest

WORKDIR /app/services/document-renderer

# Wskazujemy ścieżkę do Chromium zainstalowanego w Alpine
ENV CHROME_BIN=/usr/bin/chromium-browser

# Domyślne polecenie uruchamiające hot-reload z użyciem Air
CMD ["air", "--build.cmd", "go build -o /tmp/document-renderer ./cmd/server/main.go", "--build.bin", "/tmp/document-renderer"]